enum Code::TokenType
  LEFT_PAREN; RIGHT_PAREN; LEFT_BRACE; RIGHT_BRACE
  COMMA; DOT; MINUS; PLUS; SEMICOLON; SLASH; STAR
  BANG; BANG_EQUAL; EQUAL; EQUAL_EQUAL
  GREATER; GREATER_EQUAL; LESS; LESS_EQUAL
  IDENTIFIER; STRING; NUMBER
  AND; CLASS; ELSE; FALSE; DEFINE; FOR; IF; NIL; OR;
  PUTS; PRINT; RETURN; SUPER; SELF; TRUE; WHILE
  EOF
end
